"""Add latitude and longitude to parcels

Revision ID: 75924e2a2bb4
Revises: 
Create Date: 2025-11-22 02:10:42.252927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75924e2a2bb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('parcel', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_transaction_neighborhood'), 'transaction', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_transaction_new_owner'), 'transaction', ['new_owner'], unique=False)
    op.create_index(op.f('ix_transaction_old_owner'), 'transaction', ['old_owner'], unique=False)
    op.create_index(op.f('ix_transaction_parcel_id'), 'transaction', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_transaction_sale_date'), 'transaction', ['sale_date'], unique=False)
    op.create_index(op.f('ix_transaction_sale_price'), 'transaction', ['sale_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_sale_price'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_sale_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_parcel_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_old_owner'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_new_owner'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_neighborhood'), table_name='transaction')
    op.drop_column('parcel', 'longitude')
    op.drop_column('parcel', 'latitude')
    # ### end Alembic commands ###
