"""Add parcel FK to transactions

Revision ID: 8d96f028d470
Revises: 75924e2a2bb4
Create Date: 2025-11-22 04:31:11.722909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d96f028d470'
down_revision: Union[str, Sequence[str], None] = '75924e2a2bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_transaction_parcel_id'), table_name='transaction')
    op.create_foreign_key(None, 'transaction', 'parcel', ['parcel_id'], ['parcel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_index(op.f('ix_transaction_parcel_id'), 'transaction', ['parcel_id'], unique=False)
    # ### end Alembic commands ###
